# Generated by Django 4.2.7 on 2026-03-16 05:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("food", "🍔 Food & Dining"),
                            ("travel", "✈️ Travel"),
                            ("shopping", "🛍️ Shopping"),
                            ("bills", "💡 Bills & Utilities"),
                            ("health", "🏥 Health"),
                            ("entertainment", "🎭 Entertainment"),
                            ("others", "📦 Others"),
                        ],
                        default="others",
                        max_length=20,
                    ),
                ),
                ("date", models.DateField()),
                ("merchant", models.CharField(blank=True, max_length=200)),
                ("notes", models.TextField(blank=True)),
                (
                    "receipt_img",
                    models.ImageField(blank=True, null=True, upload_to="receipts/"),
                ),
                ("ocr_text", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-created_at"],
            },
        ),
    ]
