# Generated by Django 4.2.7 on 2026-03-16 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expense",
            name="receipt_img",
        ),
        migrations.AddField(
            model_name="expense",
            name="receipt_file",
            field=models.FileField(blank=True, null=True, upload_to="receipts/"),
        ),
    ]
