# Generated by Django 5.2.5 on 2026-04-13 16:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_remove_expense_receipt_img_expense_receipt_file"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(
                fields=["user", "date"], name="app_expense_user_id_fc40a3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(
                fields=["user", "category"], name="app_expense_user_id_7fe0cf_idx"
            ),
        ),
    ]
